POST localhost:8080/test
Content-Type: application/json

{
  "name": "cjh"
}
###
GET localhost:8080/test

###
GET localhost:8080/test/1

###
POST localhost:8080/board
Content-Type: application/json

{
  "memberId" : 1
}
###
GET localhost:8080/board/2

###
GET localhost:8080/board/2/?keyword=준혁&searchType=name&pageNum=1&pageSize=50

###

PUT localhost:8080/board/3
Content-Type: application/json

{
  "boardType" : 2,
  "subject":"변경 TEST",
  "content":"<p>변경 TEST</p>"
}

###
DELETE localhost:8080/board/3





